### ISSUE TITLE
Mapping through rows/columns in DenseMatrix

### ISSUE THREAD

**Issue by fayimora** [scalanlp/breeze#359]
I've checked the API and examples but couldn't find a way to map over rows/columns in a DenseMatrix. Is this intentional or just something that isn't implemented yet?

I was expecting an easy way to map through the rows or columns and get a `Transpose[DenseVector]` or `DenseVector` respectively in each iteration.

**Comment by dlwh** [comment]
just badly documented, I guess.

dm(*, ::).map( dv => ) maps rows
dm(::, *).map( dv => ) maps columns

-- David

**Comment by fayimora** [comment]
Hmm interesting. I tried that and got this error.

![screenshot 2015-02-01 22 13 36](https://cloud.githubusercontent.com/assets/648684/5994113/ae01add0-aa5f-11e4-9be1-fc125d6b042e.png)

**Comment by dlwh** [comment]
slicing only works on DenseMatrices right now

**Comment by dlwh** [comment]
e.g.:

```scala
scala> import breeze.linalg._
import breeze.linalg._

scala> val x = DenseMatrix.rand[Double](4,3)
x: breeze.linalg.DenseMatrix[Double] =
0.7156375701397633   0.7837784017659517   0.8970356161935793
0.789307903153093    0.3678762022777564   0.5742390722624224
0.4833611750071245   0.7833893016446367   0.8805654409248709
0.36781955949644307  0.16455169597232056  0.5630235120385354

scala> x(*, ::).map(x => 3 * 4)
res0: breeze.linalg.DenseVector[Int] = DenseVector(12, 12, 12, 12)

scala> x(*, ::).map(x => 4.0 * x)
res1: breeze.linalg.DenseMatrix[Double] =
2.862550280559053   3.135113607063807   3.588142464774317
3.157231612612372   1.4715048091110257  2.2969562890496897
1.933444700028498   3.133557206578547   3.5222617636994835
1.4712782379857723  0.6582067838892822  2.2520940481541416
```

**Comment by fayimora** [comment]
thanks @dlwh .

I'm implementing some models and I'm having to convert between Scala's collection and that of breeze in other to use Scala's lovely functions(slice, grouped, groupBy e.t.c).

Question:
* What is the cost of converting between breeze/scala collections?
* Are more functions going to be implemented for breeze's collection to match that of Scala's collections? (I'll be happy to send PRs but I'm just getting acquainted with the library.)

**Comment by gabeos** [comment]
Hey @fayimora -- David is out of contact for a bit, but I'm not sure I see the use case for implementing functions such as grouped, which seem to me to be useful mostly for collections of objects, rather than numerical vectors applied to linear algebra tasks, for which breeze is heavily optimized. I might be missing something, so if there's a strong argument to be made, I'm sure it would be considered. As it is, already the map functionality for vectors is relatively inefficient, and you're better off working with vector operations rather than on individual elements due to the off-loaded native BLAS functionality. Probably a better bet if you need it would be to define your own functions to simplify grouping, etc. on top of the slice/map operations David outlined above.

In the meantime, however, converting an Array to a DenseVector is a simple wrapping operation (O(1)), and a properly organized array to DenseMatrix via the DenseMatrix(rows,cols,Array[_]) method is the same. The DenseVector.toArray is delegated to a Java System.arraycopy, unless the stride is non-unary. DenseVector.toScalaVector is just DenseVector.toArray.toVector so it's a System.arraycopy plus the scala conversion (which i think is O(N)). 

Let me know if this helps or if you want to make an argument for implementing further collections operations.

**Comment by fayimora** [comment]
Thanks @gabeos I agree those operations are not really Linear Algebra operations and knowing that converting Array to Scala Vector and vice versa takes constant time is great! I'm ok with just converting to an array in other to perform those operations.

**Comment by dlwh** [comment]
Yeah, I'm not sure it makes sense to support the full suite of Scala
collection operations, though I could be convinced. I do intend to add
scan, at the minimum.

(And DenseVector.toArray is a linear time operation. Probably a very fast
one if you're using a unit stride, but an arraycopy nonetheless.

**Comment by aliakhtar** [comment]
How can I submit a pull request to add this to the docs?

Also, is it possible to have some more info on what exactly the `*` operator does? Be happy to add that to docs as well
