### ISSUE TITLE
NegativeArraySizeException for large matrices

### ISSUE THREAD

**Issue by pranaydoshi** [scalanlp/breeze#426]
Hi,

I'm working with a large CSCMatrix and get a NegativeArraySizeException when converting to a DenseMatrix using:
`val b = a.toDense`
because of integer overflow in the DenseMatrix.zeros method:

`def zeros[@spec(Double, Int, Float, Long) V:ClassTag:Zero](rows: Int, cols: Int): DenseMatrix[V] = {
    val data = new Array[V](rows * cols)`

 I was wondering if you guys were going to convert to Long for row and column sizes to support bigger matrices. Scala's MAX_VALUE for Int is 2147483647  which is easily reachable when dealing with big data. In this case, this number represents the total number of elements in the matrix which is quite small(For ex: you could only make a square matrix with rows = cols = 2147483647^0.5 = 46341, a really small number when dealing with big data)

**Comment by dlwh** [comment]
Eventually I'd like to, but it necessitates some huge changes to the underlying architecture (not to mention netlib-java) and it's probably not going to happen all that soon.

Probably the right thing is to use ByteBuffers, etc, instead for Dense data.

**Comment by bashimao** [comment]
@pranaydoshi: I know this is not a real solution. However, it helps avoiding errors in the long run. I use the following operator overloads during loading my data to make sure I am not going over the Int-Range.
@dlwh: You could use the <code>!*</code> operator I defined below to as a <code>require</code>-predicate during construction to make sure that there won't be overflows.

<pre>
final implicit class IntFunctions(i: Int) {

    @inline
    def ?+(other: Int): Int = {
      val result = i.toLong + other.toLong
      if (result < Int.MinValue || result > Int.MaxValue) {
        throw new ArithmeticException("Integer overflow!")
      }
      result.toInt
    }

    @inline
    def ?-(other: Int): Int = {
      val result = i.toLong - other.toLong
      if (result < Int.MinValue || result > Int.MaxValue) {
        throw new ArithmeticException("Integer overflow!")
      }
      result.toInt
    }

    @inline
    def ?*(other: Int): Int = {
      val result = i.toLong * other.toLong
      if (result < Int.MinValue || result > Int.MaxValue) {
        throw new ArithmeticException("Integer overflow!")
      }
      result.toInt
    }

    @inline
    def !*(other: Int): Boolean = {
      val result = i.toLong * other.toLong
      result >= Int.MinValue && result <= Int.MaxValue
    }
}
</pre>

**Comment by bashimao** [comment]
2147483647 is IMHO also wrong. See here:

http://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size

**Comment by pranaydoshi** [comment]
bashimao interesting, on my machine on scala REPL,if I do this:
val a = Int.MaxValue + 1
I get -2147483648
Int.MaxValue is 2147483647

**Comment by bashimao** [comment]
That is supposed to happen and is directly related with the binary encoding in your (i presume) x86 computer system. All standard operations on <code>Int</code>s produce <code>Int</code> results. On your x86 machine with (I presume) Intel x86/AMD64 instruction set <code>2147483647</code> is <code>0111 1111 1111 1111 1111 1111 1111 1111</code> in binary. Add <code>1</code> and you get <code>1000 0000 0000 0000 0000 0000 0000 0000</code> (binary) or <code>-2147483648</code> (decimal). Add <code>1</code> again, and you get <code>1000 0000 0000 0000 0000 0000 0000 0001</code> or <code>-2147483647</code>.

Although your system is theoretically able to use 64 bits to encode a number, it does not do the conversion automatically (that is why I use the <code>.toLong</code> in my code to tell the system that I want that). Actually, a lot of programmers who come from C (like me) rely on this behavior. And so the people who originally created the JVM put the responsibility to determine whether a computation result fits into a variable-type into the hands of the programmer.

So the operator-overload I defined in the code above, converts to <code>Long</code> (64-bit number) and performs the addition, subtraction or multiplication using 64-bit CPU registers. Then it checks against <code>Int</code>-boundaries (32-bit number) and raises an exception if these have been violated. If not we can safely convert back <code>toInt</code> without loosing any information.

The reason why the JVM favors <code>Int</code> (32-bit numbers) is that it was created before 64-bit hardware hit the mass market and because JVMs run (even today) on a broad spectrum of hardware including household appliances, which are equipped with the cheapest possible CPUs. Most of them are not 64-bit capable and franqly speaking: Even a very complex washing machine can do its job properly without 64-bit and a floating point unit.

As soon as one 64-bit variable participates in a computation the result will be of the larger type.

Regarding your example:
<pre>
val a = Int.MaxValue
</pre>
Result is <code>+2147483647</code>, type is <code>Int</code>.
<pre>
val a = Int.MaxValue + 1
</pre>
Result is <code>-2147483648</code>, type is <code>Int</code>.
<pre>
val a = Int.MaxValue + 0L
</pre>
Result is <code>+2147483647</code>, type is <code>Long</code>.
<pre>
val a = Int.MaxValue + 1L
</pre>
Result is <code>+2147483648</code>, type is <code>Long</code>.

**Comment by bashimao** [comment]
P.S.: Please be aware that while an array of 2 billion values of the Java-Type boolean requires about 2 GB of memory (with bit packing you could improve this by a factor of 8 without using advanced compression techniques, also see: https://github.com/scalanlp/breeze/blob/6191c015a09c7408501a93f77b5a2209c071f5e6/math/src/main/scala/breeze/linalg/BitVector.scala).

However, an array of 2 billion double values on the other hand is 16 GB large. That is quite huge, even on todays hardware. Doing calculus on such a huge dense matrix will be very slow.

**Comment by dlwh** [comment]
Yeah, the fact that you're trying to toDense something that's larger than
1<<31 is a bad sign. You're not going to be able to do anything useful with
a (dense) matrix that big.

There is a legitimate second question arising from the fact that we use Int
for size, even for sparse matrices. That leads to weird underflow problems.
