### ISSUE TITLE
How to achieve functions that are not directly supported on BigDecimal ?

### ISSUE THREAD

**Issue by KLordy** [scalanlp/breeze#514]
For example, I wanna to call exp or sigmoid on a BigDecimal collection and turned out to be reminded that it needs an implicit value impl:breeze.numerics.exp(or sigmoid).Imp.[scala.math.BigDecimal,VR].
My program needs the result of every calculation to be precise,so I have to use BigDecimal to calculate.However,it is so sad to know that many functions does not support parameters of BigDecimal type.  ;(  I think I will have to deal with circumstance frequently,how can I do each time I call a function that does not like parameters of BigDecimal type?

**Comment by dlwh** [comment]
Take a look at https://github.com/scalanlp/breeze/wiki/Universal-Functions,
particularly the section on Implementing UFuncs.

Basically, you need to put something like the following in implicit scope:

```scala
implicit object implExpBigDecimal extends exp.Impl[BigDecimal, BigDecimal] {
  def apply(v: BigDecimal): BigDecimal = ???
}
```

Now, actually implementing exp for BigDecimal is up to you. (Happy to
accept a PR!) It's not built into Java, and it seems like it's not well
defined, since e is irrational...

**Comment by KLordy** [comment]
@dlwh  I have read the source codes,and coding as you said. My codes are as below:
`implicit object implExpBigDecimal extends exp.Impl[BigDecimal,BigDecimal]{
  override def apply(v: BigDecimal): BigDecimal = java.lang.Math.exp(v.doubleValue())
}`
Through my test, I found it seems that doing like this ( transforming BigDecimal to double via v.doubleValue() and then call exp in implicit object)  will not lose accuracy. And if I do not use this implicit object and calling exp(v.doubleValue()) directly in my code seems will lose accuracy. If my test is correct, am I right to guess that it has done some operations while calling exp(v.doubleValue()) through implicit object to avoid accuracy loss. And then,is it right that I can be sure of whatever functions I call later on BigDecimal by implementing like this will not lose accuracy?(if so,it would be really perfect for me!)
Thanks for your reply.

**Comment by dlwh** [comment]
implicits aren't magic, really. There's an implicit conversion from double
to BigDecimal that's getting used:

scala> 1.0:BigDecimal
res0: BigDecimal = 1.0

To be clear, what you are doing is: converting the BigDecimal to a Double
(taking whatever accuracy loss from that), exping it (which has a very
small error), and then converting it back to BigDecimal again. So you
almost certainly will lose some precision, but there's no good way to exp
otherwise. (Are you sure you need that much precision, anyway?)

**Comment by KLordy** [comment]
ugh, maybe not need that much precision. Thanks for your explanation.
