### ISSUE TITLE
Surprising operator precedence

### ISSUE THREAD

**Issue by darabos** [scalanlp/breeze#521]
Perhaps it's trivial to everyone, but it caused me a lot of headache until I found the bug in a complex computation.

    val d = DenseVector[Double](0.5, 0.5)
    d :* d + 1.0

The square of something, plus one. That should be greater than 1, right? No. It's `DenseVector(0.75, 0.75)` because `+` has higher precedence than `:*`.

    d :* d :+ 1.0

Yeah, that's good. Maybe I should just always use `:+` and be safe?

    1.0 :+ d :* d

No, that's `DenseVector(0.75, 0.75)` again, because `:+` and `:*` have the same precedence, so it just goes from left to right.

----

Is there a way to fix this? I think there isn't.

Is there a way to detect this and assert/warn against it? Like disallowing mixing `+` and `:*` would already avoid a class of mistakes. But it's probably too much effort for a very incomplete solution.

Is it too late to deprecate and replace these operators? Using `*:` instead of `:*` would get the precedence right I think.

If all else fails, is there a way to document this prominently? Like maybe this should be mentioned in the name of the project, it's such a fundamental pitfall :).

**Comment by dlwh** [comment]
This is known and I agree pretty severe, and I intend to fix it in Breeze 0.13 by doing a deprecation cycle.

`*:`  won't work because operators ending in `:` have right associativity in Scala. So I've landed on `*:*` etc.

I'll do this at some point in the couple of months, but it's also a pretty easy thing to do. Maybe someone wants to do a PR?

**Comment by darabos** [comment]
> I'll do this at some point in the couple of months, but it's also a pretty easy thing to do. Maybe someone wants to do a PR?

Sure! I'm totally new to Breeze, but I tried my best. See #522. Thanks!

**Comment by darabos** [comment]
One more thing to think about is updating the documentation when 0.13 comes out. I'd love to remember and come back to do it at that time, but I know I will forget :).

**Comment by kenqcl** [comment]
I am using breeze 0.13.2. when use :> to compare two DenseVector, I also get "there was one deprecation warning (since 0.13)".

I checked the API doc: http://www.scalanlp.org/api/breeze/#breeze.linalg.DenseVector
':>' is not marked as deprecated.

What is the right operator to use to compare two DenseVector?

**Comment by dlwh** [comment]
`>:>`

Basically, every operator `:@` got replaced with `@:@`, except that comparison operators like `:>=` are now `>:=`

 I haven't updated the docs as darabos suggested I should. If you run with deprecation warnings turned on, it will tell you.

**Comment by kenqcl** [comment]
Thanks. Just look at the source code. There is a comment in the code says so.
`@deprecated(
    "This operator has confusing and often surprising precedence that leads to bugs. Use >:> instead.", "0.13")`

Just wondering, it will be better this kind of comment would show in API document.
or show when compiling with -deprecation option

**Comment by dlwh** [comment]
it does show up when using -deprecation. You didn't have it on...

**Comment by kenqcl** [comment]
You are right. I did not set the option right.
Thanks.
