### ISSUE TITLE
error: object plot is not a member of package breeze

### ISSUE THREAD

**Issue by aw236** [scalanlp/breeze#798]
The example code for breeze viz doesn't work.

```
import breeze.linalg._
import breeze.plot._

val f = Figure()
val p = f.subplot(0)
val x = linspace(0.0,1.0)
p += plot(x, x ^:^ 2.0)
p += plot(x, x ^:^ 3.0, '.')
p.xlabel = "x axis"
p.ylabel = "y axis"
f.saveas("lines.png") // save current figure as a .png, eps and pdf also supported
```
Gives the error: 

```
An error was encountered:
<console>:85: error: object plot is not a member of package breeze
       import breeze.plot._
```

**Comment by dlwh** [comment]
I'm guessing you haven't added the plotting library. It's a separate jar

**Comment by aw236** [comment]
@dlwh Which JAR would I need? I just installed these 2:

https://search.maven.org/search?q=a:breeze_2.13
https://search.maven.org/search?q=a:breeze-viz_2.13

**Comment by dlwh** [comment]
breeze-viz. It must not be on your classpath. How are you invoking your
script?

**Comment by aw236** [comment]
I'm working in an AWS EMR cluster and running code in an EMR Notebook attached to it. I have a script that copies the JARs to each worker node:

`sudo aws s3 cp s3://anyoung/jars/breeze-viz_2.13-1.1.jar /usr/lib/spark/jars/`
`sudo aws s3 cp s3://anyoung/jars/breeze_2.13-1.1.jar /usr/lib/spark/jars/`

Then in a Spark kernel notebook, I just do `import breeze` which works without errors.

**Comment by dlwh** [comment]
hrm, so I honestly don't use spark so you probably need to ask elsewhere
(StackOverflow or a Spark forum) but i suspect that neither jar is actually
getting picked up. Spark MLLib ships with Breeze included so I suspect
you're just getting the builtin version.

One thing to try is to run more or less the equivalent of this
https://mkyong.com/java/how-to-print-out-the-current-project-classpath/ in
your notebook and see what jars are included. That may not work because
Spark does some classloader shenanigans (it has to) but worth a try.

-- David

**Comment by dlwh** [comment]
closing b/c i don't see a way to move forward.
